import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { CURRENCY_SYMBOL } from '@/constants/theme';

interface MonthlyReportData {
  totalIncome: number;
  totalExpense: number;
  balance: number;
  month: string;
  categoryBreakdown: { category: string; amount: number }[];
}

export async function generateAndSharePDF(data: MonthlyReportData): Promise<void> {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Expense Report - ${data.month}</title>
      <style>
        body {
          font-family: system-ui, -apple-system, sans-serif;
          padding: 24px;
          max-width: 600px;
          margin: 0 auto;
        }
        h1 {
          color: #0a7ea4;
          font-size: 24px;
          margin-bottom: 24px;
        }
        .summary {
          background: #f5f5f5;
          padding: 20px;
          border-radius: 12px;
          margin-bottom: 24px;
        }
        .summary-row {
          display: flex;
          justify-content: space-between;
          padding: 8px 0;
          font-size: 16px;
        }
        .summary-row.total {
          font-weight: bold;
          font-size: 18px;
          border-top: 2px solid #ddd;
          margin-top: 8px;
          padding-top: 12px;
        }
        .income { color: #22c55e; }
        .expense { color: #ef4444; }
        .balance { color: #0a7ea4; }
        h2 {
          font-size: 18px;
          margin: 24px 0 12px;
        }
        .category-row {
          display: flex;
          justify-content: space-between;
          padding: 6px 0;
          border-bottom: 1px solid #eee;
        }
        .footer {
          margin-top: 32px;
          font-size: 12px;
          color: #888;
        }
      </style>
    </head>
    <body>
      <h1>Expense Report - ${data.month}</h1>
      <div class="summary">
        <div class="summary-row">
          <span>Total Income</span>
          <span class="income">+${CURRENCY_SYMBOL}${data.totalIncome.toFixed(2)}</span>
        </div>
        <div class="summary-row">
          <span>Total Expense</span>
          <span class="expense">-${CURRENCY_SYMBOL}${data.totalExpense.toFixed(2)}</span>
        </div>
        <div class="summary-row total">
          <span>Balance</span>
          <span class="balance">${CURRENCY_SYMBOL}${data.balance.toFixed(2)}</span>
        </div>
      </div>
      <h2>Expenses by Category</h2>
      ${
        data.categoryBreakdown.length > 0
          ? data.categoryBreakdown
              .map(
                (c) => `
        <div class="category-row">
          <span>${c.category}</span>
          <span>${CURRENCY_SYMBOL}${c.amount.toFixed(2)}</span>
        </div>
      `
              )
              .join('')
          : '<p>No expense data for this month.</p>'
      }
      <div class="footer">
        Generated by Personal Expense Tracker
      </div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `Expense Report - ${data.month}`,
    });
  }
}
